import smtplib
import base64
import sys
import csv
import mysql.connector as mariadb

mariadb_connection = mariadb.connect(user='root', password='tiger', database='test')
cursor = mariadb_connection.cursor()
cursor.execute("SELECT id,name FROM newtable")
rows = cursor.fetchall()
column_names = [i[0] for i in cursor.description]
fp = open('mariadb.csv', 'w')
myFile = csv.writer(fp)
myFile.writerow(column_names)
myFile.writerows(rows)
fp.close()

# import the corresponding modules
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

port = 2525
smtp_server = "smtp.ad.dhisco.com"
login = "1a2b3c4d5e6f7g" # paste your login generated by Mailtrap
password = "1a2b3c4d5e6f7g" # paste your password generated by Mailtrap

subject = "An example of boarding pass"
sender_email = "vaneet.kataria@rategain.com"
receiver_email = "vaneetkataria54@gmail.com"

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Add body to email
body = "This is an example of how you can send a boarding pass in attachment with Python"
message.attach(MIMEText(body, "plain"))

filename = "mariadb.csv"
# Open PDF file in binary mode

# We assume that the file is in the directory where you run your Python script from
with open(filename, "rb") as attachment:
    # The content type "application/octet-stream" means that a MIME attachment is a binary file
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode to base64
encoders.encode_base64(part)

# Add header
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to your message and convert it to string
message.attach(part)
text = message.as_string()

# send your email
with smtplib.SMTP(smtp_server, 25) as server:
    server.sendmail(
        sender_email, receiver_email, text
    )
print('Sent')

